In [3]:
#https://github.com/mrdbourke/zero-to-mastery-ml/blob/master/section-2-data-science-and-ml-tools/introduction-to-scikit-learn.ipynb
#https://github.com/mrdbourke/zero-to-mastery-ml/blob/master/section-2-data-science-and-ml-tools/introduction-to-scikit-learn-video.ipynb
#https://github.com/mrdbourke/zero-to-mastery-ml/blob/master/section-2-data-science-and-ml-tools/scikit-learn-what-were-covering.ipynb

In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
#1. Getting the Data Ready
heart_disease = pd.read_csv("https://raw.githubusercontent.com/mrdbourke/zero-to-mastery-ml/master/data/heart-disease.csv") #create Dataframe
heart_disease.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [3]:
# Splitting the data into features (X) and labels (y)
X = heart_disease.drop('target', axis=1)
y = heart_disease["target"]
X.head()
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [4]:
# Split the data into training and test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    test_size=0.2)
# Check the shapes of different data splits
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((242, 13), (61, 13), (242,), (61,))

In [5]:
# 80% of data is being used for the training set (the model will learn patterns on these samples)
X.shape[0] * 0.8

242.4

In [6]:
# And 20% of the data is being used for the testing set (the model will be evaluated on these samples)
X.shape[0] * 0.2

60.6

In [7]:
#🔥1.1 MAKE ALWAYS SURE IT'S ALL NUMERICAL, DO ENCODING🔥!! e.g. how might we turn features such as Make and Colour into numbers? ML works better w numbers than str!!
#The process of turning categorical features into numbers is often referred to as encoding.

In [8]:
car_sales = pd.read_csv("https://raw.githubusercontent.com/mrdbourke/zero-to-mastery-ml/master/data/car-sales-extended.csv") # load data directly from raw URL (source: https://github.com/mrdbourke/zero-to-mastery-ml/blob/master/data/car-sales-extended.csv)
car_sales.head()

     Make Colour  Odometer (KM)  Doors  Price
0   Honda  White          35431      4  15323
1     BMW   Blue         192714      5  19943
2   Honda  White          84714      4  28343
3  Toyota  White         154365      4  13434
4  Nissan   Blue         181577      3  14043

In [9]:
car_sales.dtypes #check the types, here you notice that 'Make' and 'Colour' features are of type object(they're strings)!!

Make               str
Colour             str
Odometer (KM)    int64
Doors            int64
Price            int64
dtype: object

In [10]:
# Split into X & y and train/test
X = car_sales.drop("Price", axis=1)
y = car_sales["Price"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [11]:
# Try to predict with random forest on price column (IT DOESN'T WORK BC of the types!!!)
#from sklearn.ensemble import RandomForestRegressor
#model = RandomForestRegressor()
#model.fit(X_train, y_train)
#model.score(X_test, y_test)

In [12]:
# 1. Import OneHotEncoder and ColumnTransformer
from sklearn.preprocessing import OneHotEncoder  #x convertire categorie in numeri e.g.Red → [1,0,0]
from sklearn.compose import ColumnTransformer   #x applicare trasformazioni diverse a colonne diverse
    #Lets you apply different transformations to different columns, very useful when you have: categorical columns → need encoding, numeric columns → leave as they are

# 2. Define the categorical features to transform
categorical_features = ["Make", "Colour", "Doors"]  #You specify which columns are categorical (these are not numbers → must be encoded)
#feat 'Door' actually is aready numerical, but the number of doors is often a different category of car e.g.you can shop for 4-door cars or shop for 5-door cars (which always confused me since where's the 5th door?)

# 3. Create an instance of OneHotEncoder
one_hot = OneHotEncoder()

# 4. Create an instance of ColumnTransformer
transformer = ColumnTransformer([("one_hot", # name, Just a label for this transformation, You can call it anything
                                  one_hot, # transformer, The actual transformation to apply, Here: OneHotEncoder
                                  categorical_features)], # columns to transform, Columns where the transformation is applied, here only "Make", "Colour", "Doors"
                                  remainder="passthrough") #tells sklearn what to do with the rest of the columns? ("passthrough" → leave unchanged, "drop" → remove them ❌) 

# 5. Turn the categorical features into numbers (this will return an array-like sparse matrix, not a DataFrame)
transformed_X = transformer.fit_transform(X)  
    #do fit()(Learns all unique categories e.g.Make → BMW, Audi, Toyota  Colour → Red, Blue, Green) and transform()(converts data into numeric format)
transformed_X

#output NOT a dataframe, but a NumPy array / sparse matrix

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.48360e+05]], shape=(1000, 13))

In [13]:
# View first transformed sample
transformed_X[0]

array([0.0000e+00, 1.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00,
       1.0000e+00, 0.0000e+00, 3.5431e+04])

In [14]:
# View original (COM'ERANO PRIMA) first sample
X.iloc[0]

Make             Honda
Colour           White
Odometer (KM)    35431
Doors                4
Name: 0, dtype: object

In [15]:
#ENCODING using pandas (used usually x small modelling experiments)
#If you're performing a larger scale modelling experiment or would like to put your data processing steps into a production pipeline, I'd recommend leaning towards Scikit-Learn, specifically a Scikit-Learn Pipeline (chaining together multiple estimator/modelling steps).
#If you're performing quick data analysis and running small modelling experiments, use PANDAS as it's generally quite fast to get up and running.

# View head of original DataFrame
car_sales.head()

# One-hot encode categorical variables
categorical_variables = ["Make", "Colour", "Doors"]
dummies = pd.get_dummies(data=car_sales[categorical_variables])  #get_dummies x transform str->int but IS BETTER One-Hot Encoder (by scikitlearn)!!
dummies

# Have to convert doors to object for dummies to work on it...
car_sales["Doors"] = car_sales["Doors"].astype(object)
dummies = pd.get_dummies(data=car_sales[["Make", "Colour", "Doors"]],
                         dtype=float)
dummies

,Make_BMW,Make_Honda,Make_Nissan,Make_Toyota,Colour_Black,Colour_Blue,Colour_Green,Colour_Red,Colour_White,Doors_3,Doors_4,Doors_5
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
1,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
4,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
995,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
996,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
997,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
998,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
999,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0

In [16]:
#ora che abbiamo fatto ENCODING di tutto quello che non era numerico (usando sklearn) recreate a train/test split USING transformed_X instead of X(original not good bc not all numerical)
from sklearn.ensemble import RandomForestRegressor

np.random.seed(42)

# Create train and test splits with transformed_X
X_train, X_test, y_train, y_test = train_test_split(transformed_X,
                                                    y,
                                                    test_size=0.2)

# Create the model instance
model = RandomForestRegressor()

# Fit the model on the numerical data (this errored before since our data wasn't fully numeric)
model.fit(X_train, y_train)

# Score the model (returns r^2 metric by default, also called coefficient of determination, higher is better)
model.score(X_test, y_test)

0.3235867221569877

In [17]:
#🔥 1.2 IF WE HAVE MISSING VALUES? WE MUST FILL THEM, OR REMOVE THEM!
#A missing value can appear as a blank, as a NaN or something similar, isn't good x a ML model!
#The practice of calculating or figuring out how to fill missing values in a dataset is called IMPUTING🔥. For a great resource on imputing missing values, I'd recommend refering to the Scikit-Learn user guide.

In [18]:
car_sales_missing = pd.read_csv("https://raw.githubusercontent.com/mrdbourke/zero-to-mastery-ml/master/data/car-sales-extended-missing-data.csv") # read directly from URL (source: https://github.com/mrdbourke/zero-to-mastery-ml/blob/master/data/car-sales-extended-missing-data.csv)
car_sales_missing.head(10)  #take first 10 rows, see that there are NaN values!!

     Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0
5   Honda    Red        42652.0    4.0  23883.0
6  Toyota   Blue       163453.0    4.0   8473.0
7   Honda  White            NaN    4.0  20306.0
8     NaN  White       130538.0    4.0   9374.0
9   Honda   Blue        51029.0    4.0  26683.0

In [19]:
# Get the sum of all missing values
car_sales_missing.isna().sum()  
#for each feature(column) get the total of NaN values. .isna() converts in True(value is missing)/False values, so .sum() sums the True(is missing) values

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [20]:
# Create features
X_missing = car_sales_missing.drop("Price", axis=1)  #.drop("Price", axis=1) → Dataframe without the target column (our label'Price') (axis=1 means the column)
print(f"Number of missing X values:\n {X_missing.isna().sum()}")

Number of missing X values:
 Make             49
Colour           50
Odometer (KM)    50
Doors            50
dtype: int64

In [21]:
# Create labels
y_missing = car_sales_missing["Price"]  #extract only the target column'Price' 
print(f"Number of missing y values: {y_missing.isna().sum()}")

Number of missing y values: 50

In [22]:
# Let's convert the categorical columns to one hot encoded (code copied from above)
# Turn the categories (Make and Colour) into numbers
from sklearn.preprocessing import OneHotEncoder  #Converts categorical data (text) into numbers
from sklearn.compose import ColumnTransformer
   #Lets you apply different transformations to different columns, very useful when you have: categorical columns → need encoding, numeric columns → leave as they are

categorical_features = ["Make", "Colour", "Doors"]  #You specify which columns are categorical (these are not numbers → must be encoded)
#feat 'Door' actually is aready numerical, but the number of doors is often a different category of car e.g.you can shop for 4-door cars or shop for 5-door cars (which always confused me since where's the 5th door?)

#Create an instance of OneHotEncoder
one_hot = OneHotEncoder()

transformer = ColumnTransformer([("one_hot",  # name, Just a label for this transformation, You can call it anything
                                  one_hot,  # transformer, The actual transformation to apply, Here: OneHotEncoder
                                  categorical_features)],  # columns to transform, Columns where the transformation is applied, here only "Make", "Colour", "Doors"
                                remainder="passthrough",  #tells sklearn what to do with the rest of the columns? ("passthrough" → leave unchanged, "drop" → remove them ❌) 
                                sparse_threshold=0) #!!controls the output format, by default OneHotEncoder returns a sparse matrix (efficient storage, mostly zeros)
                                    #sparse_threshold=0 here You force the output to be a dense NumPy array

transformed_X_missing = transformer.fit_transform(X_missing)  #do fit()(Learns all unique categories e.g.Make → BMW, Audi, Toyota  Colour → Red, Blue, Green) and transform()(converts data into numeric format)
   #here we use X_missing instead of X !!
transformed_X_missing

#output NOT a dataframe, but a NumPy array / sparse matrix

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 0.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        0.00000e+00, 2.48360e+05]], shape=(1000, 16))

In [23]:
# Split data into training and test sets BUT HERE ERROR BC we have stille some Nan (null values)!! 
#RandomForestRegressor, we'll have to either fill or remove the missing values!!
#X_train, X_test, y_train, y_test = train_test_split(transformed_X_missing,
#                                                   y_missing,
#                                                    test_size=0.2)

# Fit and score a model
#model = RandomForestRegressor()
#model.fit(X_train, y_train)
#model.score(X_test, y_test)

In [24]:
car_sales_missing.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [25]:
#1.2.1 Fill missing data with PANDAS. ora che abbiamo una panoramica dei nostri NaN values, vediamo di riempirli
#filling missing data with given or calculated values is called imputation

#we will do
#COLUMN   WHAT WE DO
#Make	  "missing"(fill w this string)
#Colour	  "missing"(fill w this string)
#Doors	  4 (fill w this number, the most common value for a car!)
#Odometer(KM)	mean of Odometer (KM)
#Price(target)	NA,remove samples missing Price  
  #alternativamente al posto di rimuovere rows where 'Price' is NaN, potremmo calcolare la media, ma cmnq here non vogliamo per ora fake labels ect

In [26]:
# Fill the missing values in the 'Make' column
# Note: In previous versions of pandas, inplace=True was possible, however this will be changed in a future version, can use reassignment instead.
# car_sales_missing["Make"].fillna(value="missing", inplace=True)

car_sales_missing["Make"] = car_sales_missing["Make"].fillna(value="missing")

In [27]:
# Fill the 'Colour' column
# Note: In previous versions of pandas, inplace=True was possible, however this will be changed in a future version, can use reassignment instead.
# car_sales_missing["Colour"].fillna(value="missing", inplace=True)

car_sales_missing["Colour"] = car_sales_missing["Colour"].fillna(value="missing")

In [28]:
#Resolve 'Doors' column

# Find the most common value of the Doors column
car_sales_missing["Doors"].value_counts()

# Fill the Doors column with the most common value
car_sales_missing["Doors"] = car_sales_missing["Doors"].fillna(value=4)

In [29]:
# Fill the 'Odometer (KM)' column
# Old: car_sales_missing["Odometer (KM)"].fillna(value=car_sales_missing["Odometer (KM)"].mean(), inplace=True)

car_sales_missing["Odometer (KM)"] = car_sales_missing["Odometer (KM)"].fillna(value=car_sales_missing["Odometer (KM)"].mean())

In [30]:
car_sales_missing.isna().sum()  #check

Make              0
Colour            0
Odometer (KM)     0
Doors             0
Price            50
dtype: int64

In [31]:
# Resolve 'Price' column .Remove rows with missing Price labels.
car_sales_missing.dropna(inplace=True)

In [32]:
car_sales_missing.isna().sum()  #check

Make             0
Colour           0
Odometer (KM)    0
Doors            0
Price            0
dtype: int64

In [33]:
# now that Dataframe is CLEAN, we can fit the model!!

# Create features
X_missing = car_sales_missing.drop("Price", axis=1)
print(f"Number of missing X values:\n{X_missing.isna().sum()}")
# Create labels
y_missing = car_sales_missing["Price"]
print(f"Number of missing y values: {y_missing.isna().sum()}")



from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
categorical_features = ["Make", "Colour", "Doors"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot", 
                                  one_hot, 
                                  categorical_features)],
                                remainder="passthrough",
                                sparse_threshold=0) # return a sparse matrix or not
transformed_X_missing = transformer.fit_transform(X_missing)
transformed_X_missing



# Split data into training and test sets
np.random.seed(42)
X_train, X_test, y_train, y_test = train_test_split(transformed_X_missing,
                                                    y_missing,
                                                    test_size=0.2)
# Fit and score a model
model = RandomForestRegressor()
model.fit(X_train, y_train)
model.score(X_test, y_test)

Number of missing X values:
Make             0
Colour           0
Odometer (KM)    0
Doors            0
dtype: int64
Number of missing y values: 0

0.22011714008302485

In [2]:
#1.2.1 Fill missing data with SCIKIT-LEARN🔥

In [3]:
car_sales_missing = pd.read_csv("https://raw.githubusercontent.com/mrdbourke/zero-to-mastery-ml/master/data/car-sales-extended-missing-data.csv") # read directly from URL (source: https://github.com/mrdbourke/zero-to-mastery-ml/blob/master/data/car-sales-extended-missing-data.csv)
car_sales_missing.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [4]:
#Resolve 'Price' column. Drop the rows with missing in the Price column
car_sales_missing.dropna(subset=["Price"], inplace=True)  
#now eliminated all rows where 'Price' was NaN

In [6]:
from sklearn.model_selection import train_test_split

# Split into X and y
X = car_sales_missing.drop("Price", axis=1)
y = car_sales_missing["Price"]

# Split data into train and test
np.random.seed(42)
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size=0.2)
#remember, SPLITTA E POI DOPO FAI I FILLS dei dati! cioe se devi fillare e.g. per column 'Color' with stringa 'missing' allora non cambia se splitti
#prima o dopo il fill, ma se invece devi fillare con VALORI NUMERICI e.g. devi fillare con la media allora DEVI SPLITTARE PRIMA xk seno riemperesti datas 
#(che magari dopo lo split finiscono nello group dei test) con dati di media che tengono conto di tutti i dati (mentre invece i 2 gruppi devono essere asettici!)!

In [8]:
from sklearn.impute import SimpleImputer  #tools x miss NaN values

# Create imputer, i will use it x column 'Make' and 'Color'
cat_imputer = SimpleImputer(strategy="constant", fill_value="missing")  
    #strategy="constant" → always replace missing values with the same value
    #fill_value="missing" → the value used is the string "missing"

# Create imputer, i will use it x column 'Doors'
door_imputer = SimpleImputer(strategy="constant", fill_value=4)   #Replaces missing values with 4

# Create imputer, i will use it x column 'Odometer (KM)'
num_imputer = SimpleImputer(strategy="mean")   #Replaces missing values with the mean (average) of the column

In [9]:
# Define different column features
#grouping target columns
categorical_features = ["Make", "Colour"]
door_feature = ["Doors"]
numerical_feature = ["Odometer (KM)"]

In [11]:
from sklearn.compose import ColumnTransformer  #x apply different transformations to different columns — all in one step.

# Create series of column transforms to perform
imputer = ColumnTransformer([
    #   "name",       transformer,    columns
    ("cat_imputer", cat_imputer, categorical_features),
    ("door_imputer", door_imputer, door_feature),
    ("num_imputer", num_imputer, numerical_feature)])

In [13]:
# Find values to fill and transform training data
filled_X_train = imputer.fit_transform(X_train)
    #.fit_transform() ->  fit = find the values to fill, transform = fill them

# Fill values in to the test set with values learned from the training set
filled_X_test = imputer.transform(X_test)

# Check filled X_train
filled_X_train

array([['Honda', 'White', 4.0, 71934.0],
       ['Toyota', 'Red', 4.0, 162665.0],
       ['Honda', 'White', 4.0, 42844.0],
       ...,
       ['Toyota', 'White', 4.0, 196225.0],
       ['Honda', 'Blue', 4.0, 133117.0],
       ['Honda', 'missing', 4.0, 150582.0]], shape=(760, 4), dtype=object)

In [15]:
# Get our transformed data array's back into DataFrame's to inspect their missing values.!!
filled_X_train_df = pd.DataFrame(filled_X_train, 
                                 columns=["Make", "Colour", "Doors", "Odometer (KM)"])

filled_X_test_df = pd.DataFrame(filled_X_test, 
                                columns=["Make", "Colour", "Doors", "Odometer (KM)"])

# Check missing data in training set
filled_X_train_df.isna().sum()

Make             0
Colour           0
Doors            0
Odometer (KM)    0
dtype: int64

In [43]:
# Check missing data in the testing set
filled_X_test_df.isna().sum()

Make             0
Colour           0
Doors            0
Odometer (KM)    0
dtype: int64

In [44]:
# Check to see the original... still missing values
car_sales_missing.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
Price             0
dtype: int64

In [16]:
filled_X_train_df.head()

#notiamo che pero column 'Make' e 'Color' sono ancora in formato string, quindi dobbiabo fare ENCODING!

     Make Colour Doors Odometer (KM)
0   Honda  White   4.0       71934.0
1  Toyota    Red   4.0      162665.0
2   Honda  White   4.0       42844.0
3   Honda  White   4.0      195829.0
4   Honda   Blue   4.0      219217.0

In [19]:
# Now let's one hot encode the features with the same code as before 
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make", "Colour", "Doors"]

one_hot = OneHotEncoder()

transformer = ColumnTransformer([("one_hot", 
                                  one_hot, 
                                  categorical_features)],
                                remainder="passthrough",
                                sparse_threshold=0) # return a sparse matrix or not

# Fill train and test values separately
transformed_X_train = transformer.fit_transform(filled_X_train_df)
transformed_X_test = transformer.transform(filled_X_test_df)

# Check transformed and filled X_train
transformed_X_train

#Now our data is all numerical & no NaN values! let's try and fit a model!

array([[0.0, 1.0, 0.0, ..., 1.0, 0.0, 71934.0],
       [0.0, 0.0, 0.0, ..., 1.0, 0.0, 162665.0],
       [0.0, 1.0, 0.0, ..., 1.0, 0.0, 42844.0],
       ...,
       [0.0, 0.0, 0.0, ..., 1.0, 0.0, 196225.0],
       [0.0, 1.0, 0.0, ..., 1.0, 0.0, 133117.0],
       [0.0, 1.0, 0.0, ..., 1.0, 0.0, 150582.0]],
      shape=(760, 15), dtype=object)

In [20]:
# Now we've transformed X, let's see if we can fit a model
np.random.seed(42)
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()

# Make sure to use the transformed data (filled and one-hot encoded X data)
model.fit(transformed_X_train, y_train)
model.score(transformed_X_test, y_test)

0.21229043336119102

In [2]:
################ continue in file '3-Try_MLmodels_forUrProblem'